### ISSUE TITLE
frontend issues

### ISSUE THREAD

**Issue by zzq5** [aayushker/Shhh#1]
After encoding or decoding is complete, the navigation bar of the page cannot be clicked.
Only refresh and then click again.

**Comment by aayushker** [comment]
Thank you for bringing this to my attention! 

I haven’t encountered this issue in my testing, but it’s possible something could be causing temporary unresponsiveness after encoding/decoding. It might be related to the process affecting the UI interaction. I’ll be looking into it to identify the root cause.

In the meantime, could you provide me with a few more details to help replicate the issue? Specifically:

Browser and version you're using.
The exact steps you took before the navbar became unresponsive.
The metadata of the image you were working with.
I’ll investigate further and keep you updated once it’s resolved!

**Comment by zzq5** [comment]
Chrome version:129.0.6668.101
title_1:Add your image and the message to hide

It may be a layout issue, when uploading an image or clicking Submit, title_1 will move upwards, blocking the navbar. When I removed title_1 elements, the problem was solved.

**Comment by aayushker** [comment]
Okay thanks for the information, I will look into the underlying problem causing this issue and patch it soon.
